// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface bbsCookieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.bbsCookie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
