// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface bbsErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.bbsError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Con.bbsError.errType errtype = 1;</code>
   */
  int getErrtypeValue();
  /**
   * <code>.Con.bbsError.errType errtype = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsError.errType getErrtype();

  /**
   * <code>string errInfo = 2;</code>
   */
  java.lang.String getErrInfo();
  /**
   * <code>string errInfo = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrInfoBytes();
}
