// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface userRegisReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.userRegisReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string pass = 2;</code>
   */
  java.lang.String getPass();
  /**
   * <code>string pass = 2;</code>
   */
  com.google.protobuf.ByteString
      getPassBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string des = 4;</code>
   */
  java.lang.String getDes();
  /**
   * <code>string des = 4;</code>
   */
  com.google.protobuf.ByteString
      getDesBytes();
}
