// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface userInResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.userInRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  boolean hasErr();
  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsError getErr();
  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder getErrOrBuilder();

  /**
   * <code>.Con.bbsCookie cookie = 2;</code>
   */
  boolean hasCookie();
  /**
   * <code>.Con.bbsCookie cookie = 2;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookie getCookie();
  /**
   * <code>.Con.bbsCookie cookie = 2;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder();
}
