// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

/**
 * <pre>
 * request type
 * </pre>
 *
 * Protobuf type {@code Con.bbsClientReq}
 */
public  final class bbsClientReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Con.bbsClientReq)
    bbsClientReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use bbsClientReq.newBuilder() to construct.
  private bbsClientReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private bbsClientReq() {
    reqtype_ = 0;
    arg_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private bbsClientReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.blinderjay.BBS.grpc.Con.bbsCookie.Builder subBuilder = null;
            if (cookie_ != null) {
              subBuilder = cookie_.toBuilder();
            }
            cookie_ = input.readMessage(com.blinderjay.BBS.grpc.Con.bbsCookie.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cookie_);
              cookie_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            reqtype_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            arg_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsClientReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsClientReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blinderjay.BBS.grpc.Con.bbsClientReq.class, com.blinderjay.BBS.grpc.Con.bbsClientReq.Builder.class);
  }

  /**
   * Protobuf enum {@code Con.bbsClientReq.reqType}
   */
  public enum reqType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>genUserInfo = 0;</code>
     */
    genUserInfo(0),
    /**
     * <code>genThreads = 1;</code>
     */
    genThreads(1),
    /**
     * <code>genPosts = 2;</code>
     */
    genPosts(2),
    /**
     * <code>chPassword = 3;</code>
     */
    chPassword(3),
    /**
     * <code>delUser = 4;</code>
     */
    delUser(4),
    /**
     * <code>delThread = 5;</code>
     */
    delThread(5),
    /**
     * <code>delPost = 6;</code>
     */
    delPost(6),
    /**
     * <code>logOut = 7;</code>
     */
    logOut(7),
    /**
     * <code>Unknown = 8;</code>
     */
    Unknown(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>genUserInfo = 0;</code>
     */
    public static final int genUserInfo_VALUE = 0;
    /**
     * <code>genThreads = 1;</code>
     */
    public static final int genThreads_VALUE = 1;
    /**
     * <code>genPosts = 2;</code>
     */
    public static final int genPosts_VALUE = 2;
    /**
     * <code>chPassword = 3;</code>
     */
    public static final int chPassword_VALUE = 3;
    /**
     * <code>delUser = 4;</code>
     */
    public static final int delUser_VALUE = 4;
    /**
     * <code>delThread = 5;</code>
     */
    public static final int delThread_VALUE = 5;
    /**
     * <code>delPost = 6;</code>
     */
    public static final int delPost_VALUE = 6;
    /**
     * <code>logOut = 7;</code>
     */
    public static final int logOut_VALUE = 7;
    /**
     * <code>Unknown = 8;</code>
     */
    public static final int Unknown_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static reqType valueOf(int value) {
      return forNumber(value);
    }

    public static reqType forNumber(int value) {
      switch (value) {
        case 0: return genUserInfo;
        case 1: return genThreads;
        case 2: return genPosts;
        case 3: return chPassword;
        case 4: return delUser;
        case 5: return delThread;
        case 6: return delPost;
        case 7: return logOut;
        case 8: return Unknown;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<reqType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        reqType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<reqType>() {
            public reqType findValueByNumber(int number) {
              return reqType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.blinderjay.BBS.grpc.Con.bbsClientReq.getDescriptor().getEnumTypes().get(0);
    }

    private static final reqType[] VALUES = values();

    public static reqType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private reqType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Con.bbsClientReq.reqType)
  }

  public static final int COOKIE_FIELD_NUMBER = 1;
  private com.blinderjay.BBS.grpc.Con.bbsCookie cookie_;
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  public boolean hasCookie() {
    return cookie_ != null;
  }
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsCookie getCookie() {
    return cookie_ == null ? com.blinderjay.BBS.grpc.Con.bbsCookie.getDefaultInstance() : cookie_;
  }
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder() {
    return getCookie();
  }

  public static final int REQTYPE_FIELD_NUMBER = 2;
  private int reqtype_;
  /**
   * <code>.Con.bbsClientReq.reqType reqtype = 2;</code>
   */
  public int getReqtypeValue() {
    return reqtype_;
  }
  /**
   * <code>.Con.bbsClientReq.reqType reqtype = 2;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType getReqtype() {
    com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType result = com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType.valueOf(reqtype_);
    return result == null ? com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType.UNRECOGNIZED : result;
  }

  public static final int ARG_FIELD_NUMBER = 3;
  private volatile java.lang.Object arg_;
  /**
   * <code>string arg = 3;</code>
   */
  public java.lang.String getArg() {
    java.lang.Object ref = arg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arg_ = s;
      return s;
    }
  }
  /**
   * <code>string arg = 3;</code>
   */
  public com.google.protobuf.ByteString
      getArgBytes() {
    java.lang.Object ref = arg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cookie_ != null) {
      output.writeMessage(1, getCookie());
    }
    if (reqtype_ != com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType.genUserInfo.getNumber()) {
      output.writeEnum(2, reqtype_);
    }
    if (!getArgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, arg_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cookie_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCookie());
    }
    if (reqtype_ != com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType.genUserInfo.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, reqtype_);
    }
    if (!getArgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, arg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blinderjay.BBS.grpc.Con.bbsClientReq)) {
      return super.equals(obj);
    }
    com.blinderjay.BBS.grpc.Con.bbsClientReq other = (com.blinderjay.BBS.grpc.Con.bbsClientReq) obj;

    boolean result = true;
    result = result && (hasCookie() == other.hasCookie());
    if (hasCookie()) {
      result = result && getCookie()
          .equals(other.getCookie());
    }
    result = result && reqtype_ == other.reqtype_;
    result = result && getArg()
        .equals(other.getArg());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCookie()) {
      hash = (37 * hash) + COOKIE_FIELD_NUMBER;
      hash = (53 * hash) + getCookie().hashCode();
    }
    hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
    hash = (53 * hash) + reqtype_;
    hash = (37 * hash) + ARG_FIELD_NUMBER;
    hash = (53 * hash) + getArg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsClientReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blinderjay.BBS.grpc.Con.bbsClientReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * request type
   * </pre>
   *
   * Protobuf type {@code Con.bbsClientReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Con.bbsClientReq)
      com.blinderjay.BBS.grpc.Con.bbsClientReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsClientReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsClientReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blinderjay.BBS.grpc.Con.bbsClientReq.class, com.blinderjay.BBS.grpc.Con.bbsClientReq.Builder.class);
    }

    // Construct using com.blinderjay.BBS.grpc.Con.bbsClientReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (cookieBuilder_ == null) {
        cookie_ = null;
      } else {
        cookie_ = null;
        cookieBuilder_ = null;
      }
      reqtype_ = 0;

      arg_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsClientReq_descriptor;
    }

    public com.blinderjay.BBS.grpc.Con.bbsClientReq getDefaultInstanceForType() {
      return com.blinderjay.BBS.grpc.Con.bbsClientReq.getDefaultInstance();
    }

    public com.blinderjay.BBS.grpc.Con.bbsClientReq build() {
      com.blinderjay.BBS.grpc.Con.bbsClientReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.blinderjay.BBS.grpc.Con.bbsClientReq buildPartial() {
      com.blinderjay.BBS.grpc.Con.bbsClientReq result = new com.blinderjay.BBS.grpc.Con.bbsClientReq(this);
      if (cookieBuilder_ == null) {
        result.cookie_ = cookie_;
      } else {
        result.cookie_ = cookieBuilder_.build();
      }
      result.reqtype_ = reqtype_;
      result.arg_ = arg_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blinderjay.BBS.grpc.Con.bbsClientReq) {
        return mergeFrom((com.blinderjay.BBS.grpc.Con.bbsClientReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blinderjay.BBS.grpc.Con.bbsClientReq other) {
      if (other == com.blinderjay.BBS.grpc.Con.bbsClientReq.getDefaultInstance()) return this;
      if (other.hasCookie()) {
        mergeCookie(other.getCookie());
      }
      if (other.reqtype_ != 0) {
        setReqtypeValue(other.getReqtypeValue());
      }
      if (!other.getArg().isEmpty()) {
        arg_ = other.arg_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.blinderjay.BBS.grpc.Con.bbsClientReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.blinderjay.BBS.grpc.Con.bbsClientReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.blinderjay.BBS.grpc.Con.bbsCookie cookie_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsCookie, com.blinderjay.BBS.grpc.Con.bbsCookie.Builder, com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder> cookieBuilder_;
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public boolean hasCookie() {
      return cookieBuilder_ != null || cookie_ != null;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsCookie getCookie() {
      if (cookieBuilder_ == null) {
        return cookie_ == null ? com.blinderjay.BBS.grpc.Con.bbsCookie.getDefaultInstance() : cookie_;
      } else {
        return cookieBuilder_.getMessage();
      }
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder setCookie(com.blinderjay.BBS.grpc.Con.bbsCookie value) {
      if (cookieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cookie_ = value;
        onChanged();
      } else {
        cookieBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder setCookie(
        com.blinderjay.BBS.grpc.Con.bbsCookie.Builder builderForValue) {
      if (cookieBuilder_ == null) {
        cookie_ = builderForValue.build();
        onChanged();
      } else {
        cookieBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder mergeCookie(com.blinderjay.BBS.grpc.Con.bbsCookie value) {
      if (cookieBuilder_ == null) {
        if (cookie_ != null) {
          cookie_ =
            com.blinderjay.BBS.grpc.Con.bbsCookie.newBuilder(cookie_).mergeFrom(value).buildPartial();
        } else {
          cookie_ = value;
        }
        onChanged();
      } else {
        cookieBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder clearCookie() {
      if (cookieBuilder_ == null) {
        cookie_ = null;
        onChanged();
      } else {
        cookie_ = null;
        cookieBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsCookie.Builder getCookieBuilder() {
      
      onChanged();
      return getCookieFieldBuilder().getBuilder();
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder() {
      if (cookieBuilder_ != null) {
        return cookieBuilder_.getMessageOrBuilder();
      } else {
        return cookie_ == null ?
            com.blinderjay.BBS.grpc.Con.bbsCookie.getDefaultInstance() : cookie_;
      }
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsCookie, com.blinderjay.BBS.grpc.Con.bbsCookie.Builder, com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder> 
        getCookieFieldBuilder() {
      if (cookieBuilder_ == null) {
        cookieBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.blinderjay.BBS.grpc.Con.bbsCookie, com.blinderjay.BBS.grpc.Con.bbsCookie.Builder, com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder>(
                getCookie(),
                getParentForChildren(),
                isClean());
        cookie_ = null;
      }
      return cookieBuilder_;
    }

    private int reqtype_ = 0;
    /**
     * <code>.Con.bbsClientReq.reqType reqtype = 2;</code>
     */
    public int getReqtypeValue() {
      return reqtype_;
    }
    /**
     * <code>.Con.bbsClientReq.reqType reqtype = 2;</code>
     */
    public Builder setReqtypeValue(int value) {
      reqtype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Con.bbsClientReq.reqType reqtype = 2;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType getReqtype() {
      com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType result = com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType.valueOf(reqtype_);
      return result == null ? com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType.UNRECOGNIZED : result;
    }
    /**
     * <code>.Con.bbsClientReq.reqType reqtype = 2;</code>
     */
    public Builder setReqtype(com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      reqtype_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Con.bbsClientReq.reqType reqtype = 2;</code>
     */
    public Builder clearReqtype() {
      
      reqtype_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object arg_ = "";
    /**
     * <code>string arg = 3;</code>
     */
    public java.lang.String getArg() {
      java.lang.Object ref = arg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getArgBytes() {
      java.lang.Object ref = arg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arg = 3;</code>
     */
    public Builder setArg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arg = 3;</code>
     */
    public Builder clearArg() {
      
      arg_ = getDefaultInstance().getArg();
      onChanged();
      return this;
    }
    /**
     * <code>string arg = 3;</code>
     */
    public Builder setArgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arg_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Con.bbsClientReq)
  }

  // @@protoc_insertion_point(class_scope:Con.bbsClientReq)
  private static final com.blinderjay.BBS.grpc.Con.bbsClientReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blinderjay.BBS.grpc.Con.bbsClientReq();
  }

  public static com.blinderjay.BBS.grpc.Con.bbsClientReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<bbsClientReq>
      PARSER = new com.google.protobuf.AbstractParser<bbsClientReq>() {
    public bbsClientReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new bbsClientReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<bbsClientReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<bbsClientReq> getParserForType() {
    return PARSER;
  }

  public com.blinderjay.BBS.grpc.Con.bbsClientReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

