// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface bbsClientReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.bbsClientReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  boolean hasCookie();
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookie getCookie();
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder();

  /**
   * <code>.Con.bbsClientReq.reqType reqtype = 2;</code>
   */
  int getReqtypeValue();
  /**
   * <code>.Con.bbsClientReq.reqType reqtype = 2;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsClientReq.reqType getReqtype();

  /**
   * <code>string arg = 3;</code>
   */
  java.lang.String getArg();
  /**
   * <code>string arg = 3;</code>
   */
  com.google.protobuf.ByteString
      getArgBytes();
}
