// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

/**
 * <pre>
 *error
 * </pre>
 *
 * Protobuf type {@code Con.bbsError}
 */
public  final class bbsError extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Con.bbsError)
    bbsErrorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use bbsError.newBuilder() to construct.
  private bbsError(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private bbsError() {
    errtype_ = 0;
    errInfo_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private bbsError(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            errtype_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            errInfo_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsError_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsError_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blinderjay.BBS.grpc.Con.bbsError.class, com.blinderjay.BBS.grpc.Con.bbsError.Builder.class);
  }

  /**
   * Protobuf enum {@code Con.bbsError.errType}
   */
  public enum errType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>err0 = 0;</code>
     */
    err0(0),
    /**
     * <code>Invalid = 1;</code>
     */
    Invalid(1),
    /**
     * <code>NoResource = 2;</code>
     */
    NoResource(2),
    /**
     * <code>Duplicate = 3;</code>
     */
    Duplicate(3),
    /**
     * <code>InfomationUncomplete = 4;</code>
     */
    InfomationUncomplete(4),
    /**
     * <code>Unknown = 5;</code>
     */
    Unknown(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>err0 = 0;</code>
     */
    public static final int err0_VALUE = 0;
    /**
     * <code>Invalid = 1;</code>
     */
    public static final int Invalid_VALUE = 1;
    /**
     * <code>NoResource = 2;</code>
     */
    public static final int NoResource_VALUE = 2;
    /**
     * <code>Duplicate = 3;</code>
     */
    public static final int Duplicate_VALUE = 3;
    /**
     * <code>InfomationUncomplete = 4;</code>
     */
    public static final int InfomationUncomplete_VALUE = 4;
    /**
     * <code>Unknown = 5;</code>
     */
    public static final int Unknown_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static errType valueOf(int value) {
      return forNumber(value);
    }

    public static errType forNumber(int value) {
      switch (value) {
        case 0: return err0;
        case 1: return Invalid;
        case 2: return NoResource;
        case 3: return Duplicate;
        case 4: return InfomationUncomplete;
        case 5: return Unknown;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<errType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        errType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<errType>() {
            public errType findValueByNumber(int number) {
              return errType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.blinderjay.BBS.grpc.Con.bbsError.getDescriptor().getEnumTypes().get(0);
    }

    private static final errType[] VALUES = values();

    public static errType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private errType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Con.bbsError.errType)
  }

  public static final int ERRTYPE_FIELD_NUMBER = 1;
  private int errtype_;
  /**
   * <code>.Con.bbsError.errType errtype = 1;</code>
   */
  public int getErrtypeValue() {
    return errtype_;
  }
  /**
   * <code>.Con.bbsError.errType errtype = 1;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsError.errType getErrtype() {
    com.blinderjay.BBS.grpc.Con.bbsError.errType result = com.blinderjay.BBS.grpc.Con.bbsError.errType.valueOf(errtype_);
    return result == null ? com.blinderjay.BBS.grpc.Con.bbsError.errType.UNRECOGNIZED : result;
  }

  public static final int ERRINFO_FIELD_NUMBER = 2;
  private volatile java.lang.Object errInfo_;
  /**
   * <code>string errInfo = 2;</code>
   */
  public java.lang.String getErrInfo() {
    java.lang.Object ref = errInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string errInfo = 2;</code>
   */
  public com.google.protobuf.ByteString
      getErrInfoBytes() {
    java.lang.Object ref = errInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (errtype_ != com.blinderjay.BBS.grpc.Con.bbsError.errType.err0.getNumber()) {
      output.writeEnum(1, errtype_);
    }
    if (!getErrInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errInfo_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errtype_ != com.blinderjay.BBS.grpc.Con.bbsError.errType.err0.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, errtype_);
    }
    if (!getErrInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errInfo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blinderjay.BBS.grpc.Con.bbsError)) {
      return super.equals(obj);
    }
    com.blinderjay.BBS.grpc.Con.bbsError other = (com.blinderjay.BBS.grpc.Con.bbsError) obj;

    boolean result = true;
    result = result && errtype_ == other.errtype_;
    result = result && getErrInfo()
        .equals(other.getErrInfo());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ERRTYPE_FIELD_NUMBER;
    hash = (53 * hash) + errtype_;
    hash = (37 * hash) + ERRINFO_FIELD_NUMBER;
    hash = (53 * hash) + getErrInfo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsError parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blinderjay.BBS.grpc.Con.bbsError prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *error
   * </pre>
   *
   * Protobuf type {@code Con.bbsError}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Con.bbsError)
      com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsError_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blinderjay.BBS.grpc.Con.bbsError.class, com.blinderjay.BBS.grpc.Con.bbsError.Builder.class);
    }

    // Construct using com.blinderjay.BBS.grpc.Con.bbsError.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      errtype_ = 0;

      errInfo_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsError_descriptor;
    }

    public com.blinderjay.BBS.grpc.Con.bbsError getDefaultInstanceForType() {
      return com.blinderjay.BBS.grpc.Con.bbsError.getDefaultInstance();
    }

    public com.blinderjay.BBS.grpc.Con.bbsError build() {
      com.blinderjay.BBS.grpc.Con.bbsError result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.blinderjay.BBS.grpc.Con.bbsError buildPartial() {
      com.blinderjay.BBS.grpc.Con.bbsError result = new com.blinderjay.BBS.grpc.Con.bbsError(this);
      result.errtype_ = errtype_;
      result.errInfo_ = errInfo_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blinderjay.BBS.grpc.Con.bbsError) {
        return mergeFrom((com.blinderjay.BBS.grpc.Con.bbsError)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blinderjay.BBS.grpc.Con.bbsError other) {
      if (other == com.blinderjay.BBS.grpc.Con.bbsError.getDefaultInstance()) return this;
      if (other.errtype_ != 0) {
        setErrtypeValue(other.getErrtypeValue());
      }
      if (!other.getErrInfo().isEmpty()) {
        errInfo_ = other.errInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.blinderjay.BBS.grpc.Con.bbsError parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.blinderjay.BBS.grpc.Con.bbsError) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int errtype_ = 0;
    /**
     * <code>.Con.bbsError.errType errtype = 1;</code>
     */
    public int getErrtypeValue() {
      return errtype_;
    }
    /**
     * <code>.Con.bbsError.errType errtype = 1;</code>
     */
    public Builder setErrtypeValue(int value) {
      errtype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Con.bbsError.errType errtype = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsError.errType getErrtype() {
      com.blinderjay.BBS.grpc.Con.bbsError.errType result = com.blinderjay.BBS.grpc.Con.bbsError.errType.valueOf(errtype_);
      return result == null ? com.blinderjay.BBS.grpc.Con.bbsError.errType.UNRECOGNIZED : result;
    }
    /**
     * <code>.Con.bbsError.errType errtype = 1;</code>
     */
    public Builder setErrtype(com.blinderjay.BBS.grpc.Con.bbsError.errType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      errtype_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Con.bbsError.errType errtype = 1;</code>
     */
    public Builder clearErrtype() {
      
      errtype_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errInfo_ = "";
    /**
     * <code>string errInfo = 2;</code>
     */
    public java.lang.String getErrInfo() {
      java.lang.Object ref = errInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrInfoBytes() {
      java.lang.Object ref = errInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errInfo = 2;</code>
     */
    public Builder setErrInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errInfo = 2;</code>
     */
    public Builder clearErrInfo() {
      
      errInfo_ = getDefaultInstance().getErrInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string errInfo = 2;</code>
     */
    public Builder setErrInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errInfo_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Con.bbsError)
  }

  // @@protoc_insertion_point(class_scope:Con.bbsError)
  private static final com.blinderjay.BBS.grpc.Con.bbsError DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blinderjay.BBS.grpc.Con.bbsError();
  }

  public static com.blinderjay.BBS.grpc.Con.bbsError getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<bbsError>
      PARSER = new com.google.protobuf.AbstractParser<bbsError>() {
    public bbsError parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new bbsError(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<bbsError> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<bbsError> getParserForType() {
    return PARSER;
  }

  public com.blinderjay.BBS.grpc.Con.bbsError getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

