// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface bbsPostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.bbsPost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  boolean hasCookie();
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookie getCookie();
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder();

  /**
   * <code>.Con.bbsError err = 2;</code>
   */
  boolean hasErr();
  /**
   * <code>.Con.bbsError err = 2;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsError getErr();
  /**
   * <code>.Con.bbsError err = 2;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder getErrOrBuilder();

  /**
   * <code>int32 pid = 3;</code>
   */
  int getPid();

  /**
   * <code>int32 tid = 4;</code>
   */
  int getTid();

  /**
   * <code>string user = 5;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 5;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string contex = 6;</code>
   */
  java.lang.String getContex();
  /**
   * <code>string contex = 6;</code>
   */
  com.google.protobuf.ByteString
      getContexBytes();

  /**
   * <code>.Con.bbsTime time = 7;</code>
   */
  boolean hasTime();
  /**
   * <code>.Con.bbsTime time = 7;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsTime getTime();
  /**
   * <code>.Con.bbsTime time = 7;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder getTimeOrBuilder();
}
