// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface bbsServerResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.bbsServerRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  boolean hasErr();
  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsError getErr();
  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder getErrOrBuilder();

  /**
   * <code>string mess = 2;</code>
   */
  java.lang.String getMess();
  /**
   * <code>string mess = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessBytes();
}
