// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

/**
 * Protobuf type {@code Con.bbsThread}
 */
public  final class bbsThread extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Con.bbsThread)
    bbsThreadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use bbsThread.newBuilder() to construct.
  private bbsThread(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private bbsThread() {
    tid_ = 0;
    user_ = "";
    topic_ = "";
    contex_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private bbsThread(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.blinderjay.BBS.grpc.Con.bbsCookie.Builder subBuilder = null;
            if (cookie_ != null) {
              subBuilder = cookie_.toBuilder();
            }
            cookie_ = input.readMessage(com.blinderjay.BBS.grpc.Con.bbsCookie.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cookie_);
              cookie_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.blinderjay.BBS.grpc.Con.bbsError.Builder subBuilder = null;
            if (err_ != null) {
              subBuilder = err_.toBuilder();
            }
            err_ = input.readMessage(com.blinderjay.BBS.grpc.Con.bbsError.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(err_);
              err_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            tid_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            user_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            contex_ = s;
            break;
          }
          case 58: {
            com.blinderjay.BBS.grpc.Con.bbsTime.Builder subBuilder = null;
            if (time_ != null) {
              subBuilder = time_.toBuilder();
            }
            time_ = input.readMessage(com.blinderjay.BBS.grpc.Con.bbsTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(time_);
              time_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsThread_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsThread_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blinderjay.BBS.grpc.Con.bbsThread.class, com.blinderjay.BBS.grpc.Con.bbsThread.Builder.class);
  }

  public static final int COOKIE_FIELD_NUMBER = 1;
  private com.blinderjay.BBS.grpc.Con.bbsCookie cookie_;
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  public boolean hasCookie() {
    return cookie_ != null;
  }
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsCookie getCookie() {
    return cookie_ == null ? com.blinderjay.BBS.grpc.Con.bbsCookie.getDefaultInstance() : cookie_;
  }
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder() {
    return getCookie();
  }

  public static final int ERR_FIELD_NUMBER = 2;
  private com.blinderjay.BBS.grpc.Con.bbsError err_;
  /**
   * <code>.Con.bbsError err = 2;</code>
   */
  public boolean hasErr() {
    return err_ != null;
  }
  /**
   * <code>.Con.bbsError err = 2;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsError getErr() {
    return err_ == null ? com.blinderjay.BBS.grpc.Con.bbsError.getDefaultInstance() : err_;
  }
  /**
   * <code>.Con.bbsError err = 2;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder getErrOrBuilder() {
    return getErr();
  }

  public static final int TID_FIELD_NUMBER = 3;
  private int tid_;
  /**
   * <code>int32 tid = 3;</code>
   */
  public int getTid() {
    return tid_;
  }

  public static final int USER_FIELD_NUMBER = 4;
  private volatile java.lang.Object user_;
  /**
   * <code>string user = 4;</code>
   */
  public java.lang.String getUser() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      user_ = s;
      return s;
    }
  }
  /**
   * <code>string user = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUserBytes() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      user_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC_FIELD_NUMBER = 5;
  private volatile java.lang.Object topic_;
  /**
   * <code>string topic = 5;</code>
   */
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>string topic = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTEX_FIELD_NUMBER = 6;
  private volatile java.lang.Object contex_;
  /**
   * <code>string contex = 6;</code>
   */
  public java.lang.String getContex() {
    java.lang.Object ref = contex_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contex_ = s;
      return s;
    }
  }
  /**
   * <code>string contex = 6;</code>
   */
  public com.google.protobuf.ByteString
      getContexBytes() {
    java.lang.Object ref = contex_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_FIELD_NUMBER = 7;
  private com.blinderjay.BBS.grpc.Con.bbsTime time_;
  /**
   * <code>.Con.bbsTime time = 7;</code>
   */
  public boolean hasTime() {
    return time_ != null;
  }
  /**
   * <code>.Con.bbsTime time = 7;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsTime getTime() {
    return time_ == null ? com.blinderjay.BBS.grpc.Con.bbsTime.getDefaultInstance() : time_;
  }
  /**
   * <code>.Con.bbsTime time = 7;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder getTimeOrBuilder() {
    return getTime();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cookie_ != null) {
      output.writeMessage(1, getCookie());
    }
    if (err_ != null) {
      output.writeMessage(2, getErr());
    }
    if (tid_ != 0) {
      output.writeInt32(3, tid_);
    }
    if (!getUserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, user_);
    }
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, topic_);
    }
    if (!getContexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, contex_);
    }
    if (time_ != null) {
      output.writeMessage(7, getTime());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cookie_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCookie());
    }
    if (err_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getErr());
    }
    if (tid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, tid_);
    }
    if (!getUserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, user_);
    }
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, topic_);
    }
    if (!getContexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, contex_);
    }
    if (time_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blinderjay.BBS.grpc.Con.bbsThread)) {
      return super.equals(obj);
    }
    com.blinderjay.BBS.grpc.Con.bbsThread other = (com.blinderjay.BBS.grpc.Con.bbsThread) obj;

    boolean result = true;
    result = result && (hasCookie() == other.hasCookie());
    if (hasCookie()) {
      result = result && getCookie()
          .equals(other.getCookie());
    }
    result = result && (hasErr() == other.hasErr());
    if (hasErr()) {
      result = result && getErr()
          .equals(other.getErr());
    }
    result = result && (getTid()
        == other.getTid());
    result = result && getUser()
        .equals(other.getUser());
    result = result && getTopic()
        .equals(other.getTopic());
    result = result && getContex()
        .equals(other.getContex());
    result = result && (hasTime() == other.hasTime());
    if (hasTime()) {
      result = result && getTime()
          .equals(other.getTime());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCookie()) {
      hash = (37 * hash) + COOKIE_FIELD_NUMBER;
      hash = (53 * hash) + getCookie().hashCode();
    }
    if (hasErr()) {
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + getErr().hashCode();
    }
    hash = (37 * hash) + TID_FIELD_NUMBER;
    hash = (53 * hash) + getTid();
    hash = (37 * hash) + USER_FIELD_NUMBER;
    hash = (53 * hash) + getUser().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + CONTEX_FIELD_NUMBER;
    hash = (53 * hash) + getContex().hashCode();
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsThread parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blinderjay.BBS.grpc.Con.bbsThread prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Con.bbsThread}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Con.bbsThread)
      com.blinderjay.BBS.grpc.Con.bbsThreadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsThread_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsThread_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blinderjay.BBS.grpc.Con.bbsThread.class, com.blinderjay.BBS.grpc.Con.bbsThread.Builder.class);
    }

    // Construct using com.blinderjay.BBS.grpc.Con.bbsThread.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (cookieBuilder_ == null) {
        cookie_ = null;
      } else {
        cookie_ = null;
        cookieBuilder_ = null;
      }
      if (errBuilder_ == null) {
        err_ = null;
      } else {
        err_ = null;
        errBuilder_ = null;
      }
      tid_ = 0;

      user_ = "";

      topic_ = "";

      contex_ = "";

      if (timeBuilder_ == null) {
        time_ = null;
      } else {
        time_ = null;
        timeBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsThread_descriptor;
    }

    public com.blinderjay.BBS.grpc.Con.bbsThread getDefaultInstanceForType() {
      return com.blinderjay.BBS.grpc.Con.bbsThread.getDefaultInstance();
    }

    public com.blinderjay.BBS.grpc.Con.bbsThread build() {
      com.blinderjay.BBS.grpc.Con.bbsThread result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.blinderjay.BBS.grpc.Con.bbsThread buildPartial() {
      com.blinderjay.BBS.grpc.Con.bbsThread result = new com.blinderjay.BBS.grpc.Con.bbsThread(this);
      if (cookieBuilder_ == null) {
        result.cookie_ = cookie_;
      } else {
        result.cookie_ = cookieBuilder_.build();
      }
      if (errBuilder_ == null) {
        result.err_ = err_;
      } else {
        result.err_ = errBuilder_.build();
      }
      result.tid_ = tid_;
      result.user_ = user_;
      result.topic_ = topic_;
      result.contex_ = contex_;
      if (timeBuilder_ == null) {
        result.time_ = time_;
      } else {
        result.time_ = timeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blinderjay.BBS.grpc.Con.bbsThread) {
        return mergeFrom((com.blinderjay.BBS.grpc.Con.bbsThread)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blinderjay.BBS.grpc.Con.bbsThread other) {
      if (other == com.blinderjay.BBS.grpc.Con.bbsThread.getDefaultInstance()) return this;
      if (other.hasCookie()) {
        mergeCookie(other.getCookie());
      }
      if (other.hasErr()) {
        mergeErr(other.getErr());
      }
      if (other.getTid() != 0) {
        setTid(other.getTid());
      }
      if (!other.getUser().isEmpty()) {
        user_ = other.user_;
        onChanged();
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getContex().isEmpty()) {
        contex_ = other.contex_;
        onChanged();
      }
      if (other.hasTime()) {
        mergeTime(other.getTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.blinderjay.BBS.grpc.Con.bbsThread parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.blinderjay.BBS.grpc.Con.bbsThread) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.blinderjay.BBS.grpc.Con.bbsCookie cookie_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsCookie, com.blinderjay.BBS.grpc.Con.bbsCookie.Builder, com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder> cookieBuilder_;
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public boolean hasCookie() {
      return cookieBuilder_ != null || cookie_ != null;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsCookie getCookie() {
      if (cookieBuilder_ == null) {
        return cookie_ == null ? com.blinderjay.BBS.grpc.Con.bbsCookie.getDefaultInstance() : cookie_;
      } else {
        return cookieBuilder_.getMessage();
      }
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder setCookie(com.blinderjay.BBS.grpc.Con.bbsCookie value) {
      if (cookieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cookie_ = value;
        onChanged();
      } else {
        cookieBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder setCookie(
        com.blinderjay.BBS.grpc.Con.bbsCookie.Builder builderForValue) {
      if (cookieBuilder_ == null) {
        cookie_ = builderForValue.build();
        onChanged();
      } else {
        cookieBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder mergeCookie(com.blinderjay.BBS.grpc.Con.bbsCookie value) {
      if (cookieBuilder_ == null) {
        if (cookie_ != null) {
          cookie_ =
            com.blinderjay.BBS.grpc.Con.bbsCookie.newBuilder(cookie_).mergeFrom(value).buildPartial();
        } else {
          cookie_ = value;
        }
        onChanged();
      } else {
        cookieBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder clearCookie() {
      if (cookieBuilder_ == null) {
        cookie_ = null;
        onChanged();
      } else {
        cookie_ = null;
        cookieBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsCookie.Builder getCookieBuilder() {
      
      onChanged();
      return getCookieFieldBuilder().getBuilder();
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder() {
      if (cookieBuilder_ != null) {
        return cookieBuilder_.getMessageOrBuilder();
      } else {
        return cookie_ == null ?
            com.blinderjay.BBS.grpc.Con.bbsCookie.getDefaultInstance() : cookie_;
      }
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsCookie, com.blinderjay.BBS.grpc.Con.bbsCookie.Builder, com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder> 
        getCookieFieldBuilder() {
      if (cookieBuilder_ == null) {
        cookieBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.blinderjay.BBS.grpc.Con.bbsCookie, com.blinderjay.BBS.grpc.Con.bbsCookie.Builder, com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder>(
                getCookie(),
                getParentForChildren(),
                isClean());
        cookie_ = null;
      }
      return cookieBuilder_;
    }

    private com.blinderjay.BBS.grpc.Con.bbsError err_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsError, com.blinderjay.BBS.grpc.Con.bbsError.Builder, com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder> errBuilder_;
    /**
     * <code>.Con.bbsError err = 2;</code>
     */
    public boolean hasErr() {
      return errBuilder_ != null || err_ != null;
    }
    /**
     * <code>.Con.bbsError err = 2;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsError getErr() {
      if (errBuilder_ == null) {
        return err_ == null ? com.blinderjay.BBS.grpc.Con.bbsError.getDefaultInstance() : err_;
      } else {
        return errBuilder_.getMessage();
      }
    }
    /**
     * <code>.Con.bbsError err = 2;</code>
     */
    public Builder setErr(com.blinderjay.BBS.grpc.Con.bbsError value) {
      if (errBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        err_ = value;
        onChanged();
      } else {
        errBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsError err = 2;</code>
     */
    public Builder setErr(
        com.blinderjay.BBS.grpc.Con.bbsError.Builder builderForValue) {
      if (errBuilder_ == null) {
        err_ = builderForValue.build();
        onChanged();
      } else {
        errBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Con.bbsError err = 2;</code>
     */
    public Builder mergeErr(com.blinderjay.BBS.grpc.Con.bbsError value) {
      if (errBuilder_ == null) {
        if (err_ != null) {
          err_ =
            com.blinderjay.BBS.grpc.Con.bbsError.newBuilder(err_).mergeFrom(value).buildPartial();
        } else {
          err_ = value;
        }
        onChanged();
      } else {
        errBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsError err = 2;</code>
     */
    public Builder clearErr() {
      if (errBuilder_ == null) {
        err_ = null;
        onChanged();
      } else {
        err_ = null;
        errBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Con.bbsError err = 2;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsError.Builder getErrBuilder() {
      
      onChanged();
      return getErrFieldBuilder().getBuilder();
    }
    /**
     * <code>.Con.bbsError err = 2;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder getErrOrBuilder() {
      if (errBuilder_ != null) {
        return errBuilder_.getMessageOrBuilder();
      } else {
        return err_ == null ?
            com.blinderjay.BBS.grpc.Con.bbsError.getDefaultInstance() : err_;
      }
    }
    /**
     * <code>.Con.bbsError err = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsError, com.blinderjay.BBS.grpc.Con.bbsError.Builder, com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder> 
        getErrFieldBuilder() {
      if (errBuilder_ == null) {
        errBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.blinderjay.BBS.grpc.Con.bbsError, com.blinderjay.BBS.grpc.Con.bbsError.Builder, com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder>(
                getErr(),
                getParentForChildren(),
                isClean());
        err_ = null;
      }
      return errBuilder_;
    }

    private int tid_ ;
    /**
     * <code>int32 tid = 3;</code>
     */
    public int getTid() {
      return tid_;
    }
    /**
     * <code>int32 tid = 3;</code>
     */
    public Builder setTid(int value) {
      
      tid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tid = 3;</code>
     */
    public Builder clearTid() {
      
      tid_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object user_ = "";
    /**
     * <code>string user = 4;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user = 4;</code>
     */
    public Builder setUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      user_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user = 4;</code>
     */
    public Builder clearUser() {
      
      user_ = getDefaultInstance().getUser();
      onChanged();
      return this;
    }
    /**
     * <code>string user = 4;</code>
     */
    public Builder setUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      user_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <code>string topic = 5;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic = 5;</code>
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 5;</code>
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 5;</code>
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contex_ = "";
    /**
     * <code>string contex = 6;</code>
     */
    public java.lang.String getContex() {
      java.lang.Object ref = contex_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contex_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contex = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContexBytes() {
      java.lang.Object ref = contex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contex = 6;</code>
     */
    public Builder setContex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contex = 6;</code>
     */
    public Builder clearContex() {
      
      contex_ = getDefaultInstance().getContex();
      onChanged();
      return this;
    }
    /**
     * <code>string contex = 6;</code>
     */
    public Builder setContexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contex_ = value;
      onChanged();
      return this;
    }

    private com.blinderjay.BBS.grpc.Con.bbsTime time_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsTime, com.blinderjay.BBS.grpc.Con.bbsTime.Builder, com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder> timeBuilder_;
    /**
     * <code>.Con.bbsTime time = 7;</code>
     */
    public boolean hasTime() {
      return timeBuilder_ != null || time_ != null;
    }
    /**
     * <code>.Con.bbsTime time = 7;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsTime getTime() {
      if (timeBuilder_ == null) {
        return time_ == null ? com.blinderjay.BBS.grpc.Con.bbsTime.getDefaultInstance() : time_;
      } else {
        return timeBuilder_.getMessage();
      }
    }
    /**
     * <code>.Con.bbsTime time = 7;</code>
     */
    public Builder setTime(com.blinderjay.BBS.grpc.Con.bbsTime value) {
      if (timeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
        onChanged();
      } else {
        timeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsTime time = 7;</code>
     */
    public Builder setTime(
        com.blinderjay.BBS.grpc.Con.bbsTime.Builder builderForValue) {
      if (timeBuilder_ == null) {
        time_ = builderForValue.build();
        onChanged();
      } else {
        timeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Con.bbsTime time = 7;</code>
     */
    public Builder mergeTime(com.blinderjay.BBS.grpc.Con.bbsTime value) {
      if (timeBuilder_ == null) {
        if (time_ != null) {
          time_ =
            com.blinderjay.BBS.grpc.Con.bbsTime.newBuilder(time_).mergeFrom(value).buildPartial();
        } else {
          time_ = value;
        }
        onChanged();
      } else {
        timeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsTime time = 7;</code>
     */
    public Builder clearTime() {
      if (timeBuilder_ == null) {
        time_ = null;
        onChanged();
      } else {
        time_ = null;
        timeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Con.bbsTime time = 7;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsTime.Builder getTimeBuilder() {
      
      onChanged();
      return getTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.Con.bbsTime time = 7;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder getTimeOrBuilder() {
      if (timeBuilder_ != null) {
        return timeBuilder_.getMessageOrBuilder();
      } else {
        return time_ == null ?
            com.blinderjay.BBS.grpc.Con.bbsTime.getDefaultInstance() : time_;
      }
    }
    /**
     * <code>.Con.bbsTime time = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsTime, com.blinderjay.BBS.grpc.Con.bbsTime.Builder, com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder> 
        getTimeFieldBuilder() {
      if (timeBuilder_ == null) {
        timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.blinderjay.BBS.grpc.Con.bbsTime, com.blinderjay.BBS.grpc.Con.bbsTime.Builder, com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder>(
                getTime(),
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      return timeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Con.bbsThread)
  }

  // @@protoc_insertion_point(class_scope:Con.bbsThread)
  private static final com.blinderjay.BBS.grpc.Con.bbsThread DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blinderjay.BBS.grpc.Con.bbsThread();
  }

  public static com.blinderjay.BBS.grpc.Con.bbsThread getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<bbsThread>
      PARSER = new com.google.protobuf.AbstractParser<bbsThread>() {
    public bbsThread parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new bbsThread(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<bbsThread> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<bbsThread> getParserForType() {
    return PARSER;
  }

  public com.blinderjay.BBS.grpc.Con.bbsThread getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

