// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface bbsUserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.bbsUserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  boolean hasCookie();
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookie getCookie();
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder();

  /**
   * <code>.Con.bbsError err = 2;</code>
   */
  boolean hasErr();
  /**
   * <code>.Con.bbsError err = 2;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsError getErr();
  /**
   * <code>.Con.bbsError err = 2;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder getErrOrBuilder();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>.Con.bbsTime lastlogintime = 5;</code>
   */
  boolean hasLastlogintime();
  /**
   * <code>.Con.bbsTime lastlogintime = 5;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsTime getLastlogintime();
  /**
   * <code>.Con.bbsTime lastlogintime = 5;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder getLastlogintimeOrBuilder();
}
