// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

/**
 * Protobuf type {@code Con.bbsUserInfo}
 */
public  final class bbsUserInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Con.bbsUserInfo)
    bbsUserInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use bbsUserInfo.newBuilder() to construct.
  private bbsUserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private bbsUserInfo() {
    uid_ = 0;
    name_ = "";
    email_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private bbsUserInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.blinderjay.BBS.grpc.Con.bbsError.Builder subBuilder = null;
            if (err_ != null) {
              subBuilder = err_.toBuilder();
            }
            err_ = input.readMessage(com.blinderjay.BBS.grpc.Con.bbsError.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(err_);
              err_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            uid_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 42: {
            com.blinderjay.BBS.grpc.Con.bbsTime.Builder subBuilder = null;
            if (lastlogintime_ != null) {
              subBuilder = lastlogintime_.toBuilder();
            }
            lastlogintime_ = input.readMessage(com.blinderjay.BBS.grpc.Con.bbsTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastlogintime_);
              lastlogintime_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsUserInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsUserInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blinderjay.BBS.grpc.Con.bbsUserInfo.class, com.blinderjay.BBS.grpc.Con.bbsUserInfo.Builder.class);
  }

  public static final int ERR_FIELD_NUMBER = 1;
  private com.blinderjay.BBS.grpc.Con.bbsError err_;
  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  public boolean hasErr() {
    return err_ != null;
  }
  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsError getErr() {
    return err_ == null ? com.blinderjay.BBS.grpc.Con.bbsError.getDefaultInstance() : err_;
  }
  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder getErrOrBuilder() {
    return getErr();
  }

  public static final int UID_FIELD_NUMBER = 2;
  private int uid_;
  /**
   * <code>int32 uid = 2;</code>
   */
  public int getUid() {
    return uid_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 4;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 4;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 4;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTLOGINTIME_FIELD_NUMBER = 5;
  private com.blinderjay.BBS.grpc.Con.bbsTime lastlogintime_;
  /**
   * <code>.Con.bbsTime lastlogintime = 5;</code>
   */
  public boolean hasLastlogintime() {
    return lastlogintime_ != null;
  }
  /**
   * <code>.Con.bbsTime lastlogintime = 5;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsTime getLastlogintime() {
    return lastlogintime_ == null ? com.blinderjay.BBS.grpc.Con.bbsTime.getDefaultInstance() : lastlogintime_;
  }
  /**
   * <code>.Con.bbsTime lastlogintime = 5;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder getLastlogintimeOrBuilder() {
    return getLastlogintime();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (err_ != null) {
      output.writeMessage(1, getErr());
    }
    if (uid_ != 0) {
      output.writeInt32(2, uid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
    }
    if (lastlogintime_ != null) {
      output.writeMessage(5, getLastlogintime());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (err_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getErr());
    }
    if (uid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, uid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
    }
    if (lastlogintime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLastlogintime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blinderjay.BBS.grpc.Con.bbsUserInfo)) {
      return super.equals(obj);
    }
    com.blinderjay.BBS.grpc.Con.bbsUserInfo other = (com.blinderjay.BBS.grpc.Con.bbsUserInfo) obj;

    boolean result = true;
    result = result && (hasErr() == other.hasErr());
    if (hasErr()) {
      result = result && getErr()
          .equals(other.getErr());
    }
    result = result && (getUid()
        == other.getUid());
    result = result && getName()
        .equals(other.getName());
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && (hasLastlogintime() == other.hasLastlogintime());
    if (hasLastlogintime()) {
      result = result && getLastlogintime()
          .equals(other.getLastlogintime());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasErr()) {
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + getErr().hashCode();
    }
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (hasLastlogintime()) {
      hash = (37 * hash) + LASTLOGINTIME_FIELD_NUMBER;
      hash = (53 * hash) + getLastlogintime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blinderjay.BBS.grpc.Con.bbsUserInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Con.bbsUserInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Con.bbsUserInfo)
      com.blinderjay.BBS.grpc.Con.bbsUserInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsUserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blinderjay.BBS.grpc.Con.bbsUserInfo.class, com.blinderjay.BBS.grpc.Con.bbsUserInfo.Builder.class);
    }

    // Construct using com.blinderjay.BBS.grpc.Con.bbsUserInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (errBuilder_ == null) {
        err_ = null;
      } else {
        err_ = null;
        errBuilder_ = null;
      }
      uid_ = 0;

      name_ = "";

      email_ = "";

      if (lastlogintimeBuilder_ == null) {
        lastlogintime_ = null;
      } else {
        lastlogintime_ = null;
        lastlogintimeBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_bbsUserInfo_descriptor;
    }

    public com.blinderjay.BBS.grpc.Con.bbsUserInfo getDefaultInstanceForType() {
      return com.blinderjay.BBS.grpc.Con.bbsUserInfo.getDefaultInstance();
    }

    public com.blinderjay.BBS.grpc.Con.bbsUserInfo build() {
      com.blinderjay.BBS.grpc.Con.bbsUserInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.blinderjay.BBS.grpc.Con.bbsUserInfo buildPartial() {
      com.blinderjay.BBS.grpc.Con.bbsUserInfo result = new com.blinderjay.BBS.grpc.Con.bbsUserInfo(this);
      if (errBuilder_ == null) {
        result.err_ = err_;
      } else {
        result.err_ = errBuilder_.build();
      }
      result.uid_ = uid_;
      result.name_ = name_;
      result.email_ = email_;
      if (lastlogintimeBuilder_ == null) {
        result.lastlogintime_ = lastlogintime_;
      } else {
        result.lastlogintime_ = lastlogintimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blinderjay.BBS.grpc.Con.bbsUserInfo) {
        return mergeFrom((com.blinderjay.BBS.grpc.Con.bbsUserInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blinderjay.BBS.grpc.Con.bbsUserInfo other) {
      if (other == com.blinderjay.BBS.grpc.Con.bbsUserInfo.getDefaultInstance()) return this;
      if (other.hasErr()) {
        mergeErr(other.getErr());
      }
      if (other.getUid() != 0) {
        setUid(other.getUid());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (other.hasLastlogintime()) {
        mergeLastlogintime(other.getLastlogintime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.blinderjay.BBS.grpc.Con.bbsUserInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.blinderjay.BBS.grpc.Con.bbsUserInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.blinderjay.BBS.grpc.Con.bbsError err_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsError, com.blinderjay.BBS.grpc.Con.bbsError.Builder, com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder> errBuilder_;
    /**
     * <code>.Con.bbsError err = 1;</code>
     */
    public boolean hasErr() {
      return errBuilder_ != null || err_ != null;
    }
    /**
     * <code>.Con.bbsError err = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsError getErr() {
      if (errBuilder_ == null) {
        return err_ == null ? com.blinderjay.BBS.grpc.Con.bbsError.getDefaultInstance() : err_;
      } else {
        return errBuilder_.getMessage();
      }
    }
    /**
     * <code>.Con.bbsError err = 1;</code>
     */
    public Builder setErr(com.blinderjay.BBS.grpc.Con.bbsError value) {
      if (errBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        err_ = value;
        onChanged();
      } else {
        errBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsError err = 1;</code>
     */
    public Builder setErr(
        com.blinderjay.BBS.grpc.Con.bbsError.Builder builderForValue) {
      if (errBuilder_ == null) {
        err_ = builderForValue.build();
        onChanged();
      } else {
        errBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Con.bbsError err = 1;</code>
     */
    public Builder mergeErr(com.blinderjay.BBS.grpc.Con.bbsError value) {
      if (errBuilder_ == null) {
        if (err_ != null) {
          err_ =
            com.blinderjay.BBS.grpc.Con.bbsError.newBuilder(err_).mergeFrom(value).buildPartial();
        } else {
          err_ = value;
        }
        onChanged();
      } else {
        errBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsError err = 1;</code>
     */
    public Builder clearErr() {
      if (errBuilder_ == null) {
        err_ = null;
        onChanged();
      } else {
        err_ = null;
        errBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Con.bbsError err = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsError.Builder getErrBuilder() {
      
      onChanged();
      return getErrFieldBuilder().getBuilder();
    }
    /**
     * <code>.Con.bbsError err = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder getErrOrBuilder() {
      if (errBuilder_ != null) {
        return errBuilder_.getMessageOrBuilder();
      } else {
        return err_ == null ?
            com.blinderjay.BBS.grpc.Con.bbsError.getDefaultInstance() : err_;
      }
    }
    /**
     * <code>.Con.bbsError err = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsError, com.blinderjay.BBS.grpc.Con.bbsError.Builder, com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder> 
        getErrFieldBuilder() {
      if (errBuilder_ == null) {
        errBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.blinderjay.BBS.grpc.Con.bbsError, com.blinderjay.BBS.grpc.Con.bbsError.Builder, com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder>(
                getErr(),
                getParentForChildren(),
                isClean());
        err_ = null;
      }
      return errBuilder_;
    }

    private int uid_ ;
    /**
     * <code>int32 uid = 2;</code>
     */
    public int getUid() {
      return uid_;
    }
    /**
     * <code>int32 uid = 2;</code>
     */
    public Builder setUid(int value) {
      
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 uid = 2;</code>
     */
    public Builder clearUid() {
      
      uid_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private com.blinderjay.BBS.grpc.Con.bbsTime lastlogintime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsTime, com.blinderjay.BBS.grpc.Con.bbsTime.Builder, com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder> lastlogintimeBuilder_;
    /**
     * <code>.Con.bbsTime lastlogintime = 5;</code>
     */
    public boolean hasLastlogintime() {
      return lastlogintimeBuilder_ != null || lastlogintime_ != null;
    }
    /**
     * <code>.Con.bbsTime lastlogintime = 5;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsTime getLastlogintime() {
      if (lastlogintimeBuilder_ == null) {
        return lastlogintime_ == null ? com.blinderjay.BBS.grpc.Con.bbsTime.getDefaultInstance() : lastlogintime_;
      } else {
        return lastlogintimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.Con.bbsTime lastlogintime = 5;</code>
     */
    public Builder setLastlogintime(com.blinderjay.BBS.grpc.Con.bbsTime value) {
      if (lastlogintimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastlogintime_ = value;
        onChanged();
      } else {
        lastlogintimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsTime lastlogintime = 5;</code>
     */
    public Builder setLastlogintime(
        com.blinderjay.BBS.grpc.Con.bbsTime.Builder builderForValue) {
      if (lastlogintimeBuilder_ == null) {
        lastlogintime_ = builderForValue.build();
        onChanged();
      } else {
        lastlogintimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Con.bbsTime lastlogintime = 5;</code>
     */
    public Builder mergeLastlogintime(com.blinderjay.BBS.grpc.Con.bbsTime value) {
      if (lastlogintimeBuilder_ == null) {
        if (lastlogintime_ != null) {
          lastlogintime_ =
            com.blinderjay.BBS.grpc.Con.bbsTime.newBuilder(lastlogintime_).mergeFrom(value).buildPartial();
        } else {
          lastlogintime_ = value;
        }
        onChanged();
      } else {
        lastlogintimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsTime lastlogintime = 5;</code>
     */
    public Builder clearLastlogintime() {
      if (lastlogintimeBuilder_ == null) {
        lastlogintime_ = null;
        onChanged();
      } else {
        lastlogintime_ = null;
        lastlogintimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Con.bbsTime lastlogintime = 5;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsTime.Builder getLastlogintimeBuilder() {
      
      onChanged();
      return getLastlogintimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.Con.bbsTime lastlogintime = 5;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder getLastlogintimeOrBuilder() {
      if (lastlogintimeBuilder_ != null) {
        return lastlogintimeBuilder_.getMessageOrBuilder();
      } else {
        return lastlogintime_ == null ?
            com.blinderjay.BBS.grpc.Con.bbsTime.getDefaultInstance() : lastlogintime_;
      }
    }
    /**
     * <code>.Con.bbsTime lastlogintime = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsTime, com.blinderjay.BBS.grpc.Con.bbsTime.Builder, com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder> 
        getLastlogintimeFieldBuilder() {
      if (lastlogintimeBuilder_ == null) {
        lastlogintimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.blinderjay.BBS.grpc.Con.bbsTime, com.blinderjay.BBS.grpc.Con.bbsTime.Builder, com.blinderjay.BBS.grpc.Con.bbsTimeOrBuilder>(
                getLastlogintime(),
                getParentForChildren(),
                isClean());
        lastlogintime_ = null;
      }
      return lastlogintimeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Con.bbsUserInfo)
  }

  // @@protoc_insertion_point(class_scope:Con.bbsUserInfo)
  private static final com.blinderjay.BBS.grpc.Con.bbsUserInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blinderjay.BBS.grpc.Con.bbsUserInfo();
  }

  public static com.blinderjay.BBS.grpc.Con.bbsUserInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<bbsUserInfo>
      PARSER = new com.google.protobuf.AbstractParser<bbsUserInfo>() {
    public bbsUserInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new bbsUserInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<bbsUserInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<bbsUserInfo> getParserForType() {
    return PARSER;
  }

  public com.blinderjay.BBS.grpc.Con.bbsUserInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

