// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public final class ContactService {
  private ContactService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_bbsCookie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_bbsCookie_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_bbsTime_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_bbsTime_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_bbsError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_bbsError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_bbsClientReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_bbsClientReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_bbsServerRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_bbsServerRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_userRegisReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_userRegisReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_userLoginReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_userLoginReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_userInRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_userInRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_bbsUserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_bbsUserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_bbsThread_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_bbsThread_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_bbsPost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_bbsPost_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_userinfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_userinfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Con_userinfoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Con_userinfoReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ContactService.proto\022\003Con\"(\n\tbbsCookie" +
      "\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"a\n\007bbsTime" +
      "\022\014\n\004year\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\013\n\003day\030\003 \001" +
      "(\005\022\014\n\004hour\030\004 \001(\005\022\016\n\006minute\030\005 \001(\005\022\016\n\006seco" +
      "nd\030\006 \001(\005\"\253\001\n\010bbsError\022&\n\007errtype\030\001 \001(\0162\025" +
      ".Con.bbsError.errType\022\017\n\007errInfo\030\002 \001(\t\"f" +
      "\n\007errType\022\010\n\004err0\020\000\022\013\n\007Invalid\020\001\022\016\n\nNoRe" +
      "source\020\002\022\r\n\tDuplicate\020\003\022\030\n\024InfomationUnc" +
      "omplete\020\004\022\013\n\007Unknown\020\005\"\364\001\n\014bbsClientReq\022" +
      "\036\n\006cookie\030\001 \001(\0132\016.Con.bbsCookie\022*\n\007reqty" +
      "pe\030\002 \001(\0162\031.Con.bbsClientReq.reqType\022\013\n\003a" +
      "rg\030\003 \001(\t\"\212\001\n\007reqType\022\017\n\013genUserInfo\020\000\022\016\n" +
      "\ngenThreads\020\001\022\014\n\010genPosts\020\002\022\016\n\nchPasswor" +
      "d\020\003\022\013\n\007delUser\020\004\022\r\n\tdelThread\020\005\022\013\n\007delPo" +
      "st\020\006\022\n\n\006logOut\020\007\022\013\n\007Unknown\020\010\"8\n\014bbsServ" +
      "erRes\022\032\n\003err\030\001 \001(\0132\r.Con.bbsError\022\014\n\004mes" +
      "s\030\002 \001(\t\"F\n\014userRegisReq\022\r\n\005email\030\001 \001(\t\022\014" +
      "\n\004pass\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\013\n\003des\030\004 \001(\t\"" +
      "+\n\014userLoginReq\022\r\n\005email\030\001 \001(\t\022\014\n\004pass\030\002" +
      " \001(\t\"G\n\tuserInRes\022\032\n\003err\030\001 \001(\0132\r.Con.bbs" +
      "Error\022\036\n\006cookie\030\002 \001(\0132\016.Con.bbsCookie\"x\n" +
      "\013bbsUserInfo\022\032\n\003err\030\001 \001(\0132\r.Con.bbsError" +
      "\022\013\n\003uid\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\r\n\005email\030\004 \001" +
      "(\t\022#\n\rlastlogintime\030\005 \001(\0132\014.Con.bbsTime\"" +
      "}\n\tbbsThread\022\032\n\003err\030\001 \001(\0132\r.Con.bbsError" +
      "\022\013\n\003tid\030\002 \001(\005\022\014\n\004user\030\003 \001(\t\022\r\n\005topic\030\004 \001" +
      "(\t\022\016\n\006contex\030\005 \001(\t\022\032\n\004time\030\006 \001(\0132\014.Con.b" +
      "bsTime\"y\n\007bbsPost\022\032\n\003err\030\001 \001(\0132\r.Con.bbs" +
      "Error\022\013\n\003pid\030\002 \001(\005\022\013\n\003tid\030\003 \001(\005\022\014\n\004user\030" +
      "\004 \001(\t\022\016\n\006contex\030\005 \001(\t\022\032\n\004time\030\006 \001(\0132\014.Co" +
      "n.bbsTime\"-\n\013userinfoReq\022\036\n\006cookie\030\001 \001(\013" +
      "2\016.Con.bbsCookie\"G\n\ruserinfoReply\022\032\n\003err" +
      "\030\001 \001(\0132\r.Con.bbsError\022\r\n\005email\030\002 \001(\t\022\013\n\003" +
      "des\030\003 \001(\t2\260\005\n\007BBS_Con\0223\n\014userRegister\022\021." +
      "Con.userRegisReq\032\016.Con.userInRes\"\000\0220\n\tus" +
      "erLogin\022\021.Con.userLoginReq\032\016.Con.userInR" +
      "es\"\000\0224\n\nuserLogout\022\021.Con.bbsClientReq\032\021." +
      "Con.bbsServerRes\"\000\0224\n\013getUserInfo\022\021.Con." +
      "bbsClientReq\032\020.Con.bbsUserInfo\"\000\0223\n\ngetT" +
      "hreads\022\021.Con.bbsClientReq\032\016.Con.bbsThrea" +
      "d\"\0000\001\022/\n\010genPosts\022\021.Con.bbsClientReq\032\014.C" +
      "on.bbsPost\"\0000\001\0228\n\017refreshUserInfo\022\020.Con." +
      "bbsUserInfo\032\021.Con.bbsServerRes\"\000\0221\n\npush" +
      "Thread\022\016.Con.bbsThread\032\021.Con.bbsServerRe" +
      "s\"\000\022.\n\tpushPosts\022\014.Con.bbsPost\032\021.Con.bbs" +
      "ServerRes\"\000\0223\n\tdelThread\022\021.Con.bbsClient" +
      "Req\032\021.Con.bbsServerRes\"\000\0221\n\007delPost\022\021.Co" +
      "n.bbsClientReq\032\021.Con.bbsServerRes\"\000\0224\n\nc" +
      "hPassword\022\021.Con.bbsClientReq\032\021.Con.bbsSe" +
      "rverRes\"\000\0221\n\007getinfo\022\020.Con.userinfoReq\032\022" +
      ".Con.userinfoReply\"\000B\037\n\033com.blinderjay.B" +
      "BS.grpc.ConP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Con_bbsCookie_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Con_bbsCookie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_bbsCookie_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_Con_bbsTime_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Con_bbsTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_bbsTime_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", "Hour", "Minute", "Second", });
    internal_static_Con_bbsError_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Con_bbsError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_bbsError_descriptor,
        new java.lang.String[] { "Errtype", "ErrInfo", });
    internal_static_Con_bbsClientReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Con_bbsClientReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_bbsClientReq_descriptor,
        new java.lang.String[] { "Cookie", "Reqtype", "Arg", });
    internal_static_Con_bbsServerRes_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Con_bbsServerRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_bbsServerRes_descriptor,
        new java.lang.String[] { "Err", "Mess", });
    internal_static_Con_userRegisReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Con_userRegisReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_userRegisReq_descriptor,
        new java.lang.String[] { "Email", "Pass", "Name", "Des", });
    internal_static_Con_userLoginReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Con_userLoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_userLoginReq_descriptor,
        new java.lang.String[] { "Email", "Pass", });
    internal_static_Con_userInRes_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Con_userInRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_userInRes_descriptor,
        new java.lang.String[] { "Err", "Cookie", });
    internal_static_Con_bbsUserInfo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Con_bbsUserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_bbsUserInfo_descriptor,
        new java.lang.String[] { "Err", "Uid", "Name", "Email", "Lastlogintime", });
    internal_static_Con_bbsThread_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Con_bbsThread_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_bbsThread_descriptor,
        new java.lang.String[] { "Err", "Tid", "User", "Topic", "Contex", "Time", });
    internal_static_Con_bbsPost_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Con_bbsPost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_bbsPost_descriptor,
        new java.lang.String[] { "Err", "Pid", "Tid", "User", "Contex", "Time", });
    internal_static_Con_userinfoReq_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Con_userinfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_userinfoReq_descriptor,
        new java.lang.String[] { "Cookie", });
    internal_static_Con_userinfoReply_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Con_userinfoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Con_userinfoReply_descriptor,
        new java.lang.String[] { "Err", "Email", "Des", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
