// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface userinfoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.userinfoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  boolean hasErr();
  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsError getErr();
  /**
   * <code>.Con.bbsError err = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsErrorOrBuilder getErrOrBuilder();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string des = 3;</code>
   */
  java.lang.String getDes();
  /**
   * <code>string des = 3;</code>
   */
  com.google.protobuf.ByteString
      getDesBytes();
}
