// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface userinfoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.userinfoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  boolean hasCookie();
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookie getCookie();
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder();
}
