// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

/**
 * <pre>
 * about user request
 * </pre>
 *
 * Protobuf type {@code Con.userinfoReq}
 */
public  final class userinfoReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Con.userinfoReq)
    userinfoReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use userinfoReq.newBuilder() to construct.
  private userinfoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private userinfoReq() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private userinfoReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.blinderjay.BBS.grpc.Con.bbsCookie.Builder subBuilder = null;
            if (cookie_ != null) {
              subBuilder = cookie_.toBuilder();
            }
            cookie_ = input.readMessage(com.blinderjay.BBS.grpc.Con.bbsCookie.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cookie_);
              cookie_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_userinfoReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_userinfoReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.blinderjay.BBS.grpc.Con.userinfoReq.class, com.blinderjay.BBS.grpc.Con.userinfoReq.Builder.class);
  }

  public static final int COOKIE_FIELD_NUMBER = 1;
  private com.blinderjay.BBS.grpc.Con.bbsCookie cookie_;
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  public boolean hasCookie() {
    return cookie_ != null;
  }
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsCookie getCookie() {
    return cookie_ == null ? com.blinderjay.BBS.grpc.Con.bbsCookie.getDefaultInstance() : cookie_;
  }
  /**
   * <code>.Con.bbsCookie cookie = 1;</code>
   */
  public com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder() {
    return getCookie();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cookie_ != null) {
      output.writeMessage(1, getCookie());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cookie_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCookie());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.blinderjay.BBS.grpc.Con.userinfoReq)) {
      return super.equals(obj);
    }
    com.blinderjay.BBS.grpc.Con.userinfoReq other = (com.blinderjay.BBS.grpc.Con.userinfoReq) obj;

    boolean result = true;
    result = result && (hasCookie() == other.hasCookie());
    if (hasCookie()) {
      result = result && getCookie()
          .equals(other.getCookie());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCookie()) {
      hash = (37 * hash) + COOKIE_FIELD_NUMBER;
      hash = (53 * hash) + getCookie().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.blinderjay.BBS.grpc.Con.userinfoReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.blinderjay.BBS.grpc.Con.userinfoReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * about user request
   * </pre>
   *
   * Protobuf type {@code Con.userinfoReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Con.userinfoReq)
      com.blinderjay.BBS.grpc.Con.userinfoReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_userinfoReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_userinfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blinderjay.BBS.grpc.Con.userinfoReq.class, com.blinderjay.BBS.grpc.Con.userinfoReq.Builder.class);
    }

    // Construct using com.blinderjay.BBS.grpc.Con.userinfoReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (cookieBuilder_ == null) {
        cookie_ = null;
      } else {
        cookie_ = null;
        cookieBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.blinderjay.BBS.grpc.Con.ContactService.internal_static_Con_userinfoReq_descriptor;
    }

    public com.blinderjay.BBS.grpc.Con.userinfoReq getDefaultInstanceForType() {
      return com.blinderjay.BBS.grpc.Con.userinfoReq.getDefaultInstance();
    }

    public com.blinderjay.BBS.grpc.Con.userinfoReq build() {
      com.blinderjay.BBS.grpc.Con.userinfoReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.blinderjay.BBS.grpc.Con.userinfoReq buildPartial() {
      com.blinderjay.BBS.grpc.Con.userinfoReq result = new com.blinderjay.BBS.grpc.Con.userinfoReq(this);
      if (cookieBuilder_ == null) {
        result.cookie_ = cookie_;
      } else {
        result.cookie_ = cookieBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.blinderjay.BBS.grpc.Con.userinfoReq) {
        return mergeFrom((com.blinderjay.BBS.grpc.Con.userinfoReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.blinderjay.BBS.grpc.Con.userinfoReq other) {
      if (other == com.blinderjay.BBS.grpc.Con.userinfoReq.getDefaultInstance()) return this;
      if (other.hasCookie()) {
        mergeCookie(other.getCookie());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.blinderjay.BBS.grpc.Con.userinfoReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.blinderjay.BBS.grpc.Con.userinfoReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.blinderjay.BBS.grpc.Con.bbsCookie cookie_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsCookie, com.blinderjay.BBS.grpc.Con.bbsCookie.Builder, com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder> cookieBuilder_;
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public boolean hasCookie() {
      return cookieBuilder_ != null || cookie_ != null;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsCookie getCookie() {
      if (cookieBuilder_ == null) {
        return cookie_ == null ? com.blinderjay.BBS.grpc.Con.bbsCookie.getDefaultInstance() : cookie_;
      } else {
        return cookieBuilder_.getMessage();
      }
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder setCookie(com.blinderjay.BBS.grpc.Con.bbsCookie value) {
      if (cookieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cookie_ = value;
        onChanged();
      } else {
        cookieBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder setCookie(
        com.blinderjay.BBS.grpc.Con.bbsCookie.Builder builderForValue) {
      if (cookieBuilder_ == null) {
        cookie_ = builderForValue.build();
        onChanged();
      } else {
        cookieBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder mergeCookie(com.blinderjay.BBS.grpc.Con.bbsCookie value) {
      if (cookieBuilder_ == null) {
        if (cookie_ != null) {
          cookie_ =
            com.blinderjay.BBS.grpc.Con.bbsCookie.newBuilder(cookie_).mergeFrom(value).buildPartial();
        } else {
          cookie_ = value;
        }
        onChanged();
      } else {
        cookieBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public Builder clearCookie() {
      if (cookieBuilder_ == null) {
        cookie_ = null;
        onChanged();
      } else {
        cookie_ = null;
        cookieBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsCookie.Builder getCookieBuilder() {
      
      onChanged();
      return getCookieFieldBuilder().getBuilder();
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    public com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder getCookieOrBuilder() {
      if (cookieBuilder_ != null) {
        return cookieBuilder_.getMessageOrBuilder();
      } else {
        return cookie_ == null ?
            com.blinderjay.BBS.grpc.Con.bbsCookie.getDefaultInstance() : cookie_;
      }
    }
    /**
     * <code>.Con.bbsCookie cookie = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.blinderjay.BBS.grpc.Con.bbsCookie, com.blinderjay.BBS.grpc.Con.bbsCookie.Builder, com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder> 
        getCookieFieldBuilder() {
      if (cookieBuilder_ == null) {
        cookieBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.blinderjay.BBS.grpc.Con.bbsCookie, com.blinderjay.BBS.grpc.Con.bbsCookie.Builder, com.blinderjay.BBS.grpc.Con.bbsCookieOrBuilder>(
                getCookie(),
                getParentForChildren(),
                isClean());
        cookie_ = null;
      }
      return cookieBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Con.userinfoReq)
  }

  // @@protoc_insertion_point(class_scope:Con.userinfoReq)
  private static final com.blinderjay.BBS.grpc.Con.userinfoReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.blinderjay.BBS.grpc.Con.userinfoReq();
  }

  public static com.blinderjay.BBS.grpc.Con.userinfoReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<userinfoReq>
      PARSER = new com.google.protobuf.AbstractParser<userinfoReq>() {
    public userinfoReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new userinfoReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<userinfoReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<userinfoReq> getParserForType() {
    return PARSER;
  }

  public com.blinderjay.BBS.grpc.Con.userinfoReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

