// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactService.proto

package com.blinderjay.BBS.grpc.Con;

public interface userLoginReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Con.userLoginReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string pass = 2;</code>
   */
  java.lang.String getPass();
  /**
   * <code>string pass = 2;</code>
   */
  com.google.protobuf.ByteString
      getPassBytes();
}
